print('Welcome - this is your personal to-do list')
print(' ')
name = input('What is your name?')
print ('Welcome',name,'.Lets start the application')
print(' ')
print('What do you want to do?')
print('CHOOSE:')

print('1. add an item')
print('2. remove an item')
print('3. show part of a list')
print('4. show entire list')
print('5. exit')
option = int(input('>>>'))
